version: "v1.0.1"
name: "pink"
# 分为dev模式与release模式
mode: "dev"
port: 8080
# 文件上传
video_size: 100
pic_size: 1
# 雪花算法
start_time: "2006-01-02"
machine_id: 1
# 每几秒钟放多少令牌
rate_limit_time: 1
rate_limit_num: 10000

auth:
  # 一年时间
  jwt_expire: 8760

log:
  level: "debug"
  filename: "logs/system/pink.log"
  userClickFileName: "logs/user_click/"
  max_size: 100
  max_age: 30
  max_backups: 10

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "zhaolu123"
  dbname: "pink"
  max_open_conns: 100
  max_idle_conns: 10

redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
  pool_size: 200

oss:
  endpoint: "oss-cn-sh12anghai.aliyu12ncs.com"
  access_key_id: ""
  access_key_secret: ""
  bucket_name: ""
  bucket_point: ""

email:
  user: "admin@otakusns.com"
  username: ""
  password: ""
  host: "smtpdm.aliyun.com"
  reply_email: "izhaicy@163.com"
